### ISSUE TITLE
About trams and ships

### ISSUE THREAD

**Issue by Fedsd1** [Hellohi3654/Geyser#172] opened 2020-11-04 23:13 UTC
Players can't take trams or boats. The original geyser doesn't have this problem

**Comment by Hellohi3654** [comment] 2020-11-05 03:08
I will look into a fix when I next update

**Comment by Hellohi3654** [comment] 2020-11-07 01:06
I believe the problem is caused by heath123's move fixes
I have got the boats to work some what
You have to spam the enter and exit buttons a couple of times then it will allow you to stay sitting in the boat

**Comment by Hellohi3654** [comment] 2020-11-19 06:43
is this still a issue?

**Comment by Hellohi3654** [comment] 2020-11-22 11:51
I believe this issue is now fixed

**Closed as completed by Hellohi3654** 2020-11-22 11:51 UTC
